// _BBPythonPatchUI_EOArchive_English.java
// Generated by EnterpriseObjects palette at Sunday, 8 July 2007 11:08:30 Europe/London

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _BBPythonPatchUI_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    BBPythonTextEditor _nsCustomView0;
    com.webobjects.eointerface.swing.EOTextArea _nsTextView0;
    com.webobjects.eointerface.swing.EOTextField _nsTextField0, _nsTextField1;
    javax.swing.JButton _nsButton0, _nsButton1, _nsButton2, _nsButton3, _nsButton4;

    public _BBPythonPatchUI_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField21");
        _nsButton4 = (javax.swing.JButton)_registered(new javax.swing.JButton("-"), "");
        _nsButton3 = (javax.swing.JButton)_registered(new javax.swing.JButton("+"), "");
        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");
        _nsButton2 = (javax.swing.JButton)_registered(new javax.swing.JButton("-"), "");
        _nsButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton("+"), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "view")) != null)) {
            _nsCustomView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (BBPythonTextEditor)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView0");
        } else {
            _nsCustomView0 = (BBPythonTextEditor)_registered(new BBPythonTextEditor(), "View");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "textview")) != null)) {
            _nsTextView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextArea)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextView0");
        } else {
            _nsTextView0 = (com.webobjects.eointerface.swing.EOTextArea)_registered(new com.webobjects.eointerface.swing.EOTextArea(), "NSTextView");
        }

        _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("Execute"), "NSButton");
    }

    protected void _awaken() {
        super._awaken();
        _nsButton4.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "removeOutputPort", _nsButton4), ""));
        _nsButton3.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "addOutputPort", _nsButton3), ""));
        _nsButton2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "removeInputPort", _nsButton2), ""));
        _nsButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "addInputPort", _nsButton1), ""));

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            _connect(_owner(), _nsCustomView0, "view");
        }

        if (_replacedObjects.objectForKey("_nsTextView0") == null) {
            _connect(_nsTextView0, _owner(), "delegate");
        }

        if (_replacedObjects.objectForKey("_nsTextView0") == null) {
            _connect(_owner(), _nsTextView0, "textview");
        }

        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "execute", _nsButton0), ""));
    }

    protected void _init() {
        super._init();
        _setFontForComponent(_nsTextField1, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField1.setEditable(false);
        _nsTextField1.setOpaque(false);
        _nsTextField1.setText("Outputs");
        _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField1.setSelectable(false);
        _nsTextField1.setEnabled(true);
        _nsTextField1.setBorder(null);
        _setFontForComponent(_nsButton4, "Lucida Grande", 11, Font.PLAIN + Font.BOLD);
        _nsButton4.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton3, "Lucida Grande", 11, Font.PLAIN + Font.BOLD);
        _nsButton3.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsTextField0, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField0.setEditable(false);
        _nsTextField0.setOpaque(false);
        _nsTextField0.setText("Inputs");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField0.setSelectable(false);
        _nsTextField0.setEnabled(true);
        _nsTextField0.setBorder(null);
        _setFontForComponent(_nsButton2, "Lucida Grande", 11, Font.PLAIN + Font.BOLD);
        _nsButton2.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton1, "Lucida Grande", 11, Font.PLAIN + Font.BOLD);
        _nsButton1.setMargin(new Insets(0, 2, 0, 2));

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            if (!(_nsCustomView0.getLayout() instanceof EOViewLayout)) { _nsCustomView0.setLayout(new EOViewLayout()); }
            _nsButton1.setSize(18, 18);
            _nsButton1.setLocation(20, 19);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsButton1);
            _nsButton2.setSize(18, 18);
            _nsButton2.setLocation(37, 19);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsButton2, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsButton2);
            _nsTextField0.setSize(50, 14);
            _nsTextField0.setLocation(61, 21);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsTextField0);
            _nsButton3.setSize(18, 18);
            _nsButton3.setLocation(115, 19);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsButton3, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsButton3);
            _nsButton4.setSize(18, 18);
            _nsButton4.setLocation(132, 19);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsButton4, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsButton4);
            _nsTextField1.setSize(50, 14);
            _nsTextField1.setLocation(156, 21);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
            _nsCustomView0.add(_nsTextField1);
            _nsTextView0.setSize(412, 395);
            _nsTextView0.setLocation(20, 43);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
            _nsCustomView0.add(_nsTextView0);
            _nsButton0.setSize(73, 16);
            _nsButton0.setLocation(358, 453);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinXMargin | EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsButton0);
        }

        if (_replacedObjects.objectForKey("_nsTextView0") == null) {
            _nsTextView0.setEditable(true);
            _nsTextView0.setOpaque(true);
            _nsTextView0.setText("Blah Blah\n");
            _setFontForComponent(_nsTextView0.textArea(), "Helvetica", 12, Font.PLAIN + Font.ITALIC);
        }

        _setFontForComponent(_nsButton0, "Lucida Grande", 9, Font.PLAIN);
        _nsButton0.setMargin(new Insets(0, 2, 0, 2));
    }
}
